import React from 'react';
import { useLocation, Link, useNavigate } from 'react-router-dom';
import { Sparkles, ArrowLeft, CheckCircle2, XCircle, ShieldCheck, Cpu } from 'lucide-react';

const MLResults = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const predictionData = location.state?.prediction;
  const inputData = location.state?.inputData;

  if (!predictionData) {
    return (
      <div style={{ padding: '3rem', textAlign: 'center' }}>
        <h2 style={{ color: 'var(--text-muted)' }}>No prediction result found in session context.</h2>
        <button onClick={() => navigate('/ml-predict')} className="btn btn-primary" style={{ marginTop: '1rem' }}>
          Go to ML Prediction Form
        </button>
      </div>
    );
  }

  const isPositive = predictionData.prediction === 1;

  return (
    <div>
      <div style={{ marginBottom: '1.5rem' }}>
        <Link to="/ml-predict" style={{ color: 'var(--primary)', fontSize: '0.85rem', fontWeight: '600', textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: '0.4rem', marginBottom: '0.5rem' }}>
          <ArrowLeft size={16} /> Predict Another Customer
        </Link>
        <h1 style={{ fontSize: '1.75rem', fontWeight: '800', color: '#fff' }}>ML Prediction Evaluation Report</h1>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>Generated by XGBoost Machine Learning Engine</p>
      </div>

      {/* Main Prediction Result Card */}
      <div className="card" style={{
        background: isPositive
          ? 'linear-gradient(135deg, rgba(16, 185, 129, 0.15), rgba(6, 182, 212, 0.15))'
          : 'linear-gradient(135deg, rgba(239, 68, 68, 0.15), rgba(245, 158, 11, 0.15))',
        border: `1px solid ${isPositive ? 'rgba(16, 185, 129, 0.4)' : 'rgba(239, 68, 68, 0.4)'}`,
        padding: '2.5rem',
        marginBottom: '2rem'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '1.5rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem' }}>
            <div style={{
              width: '72px',
              height: '72px',
              borderRadius: '20px',
              background: isPositive ? 'rgba(16, 185, 129, 0.25)' : 'rgba(239, 68, 68, 0.25)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: isPositive ? '#34d399' : '#f87171'
            }}>
              {isPositive ? <CheckCircle2 size={42} /> : <XCircle size={42} />}
            </div>

            <div>
              <div style={{ fontSize: '0.8rem', fontWeight: '700', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                AI Model Prediction Output
              </div>
              <div style={{ fontSize: '2.2rem', fontWeight: '800', color: '#fff', marginTop: '0.2rem' }}>
                {predictionData.prediction_label}
              </div>
              <div style={{ fontSize: '0.9rem', color: isPositive ? '#34d399' : '#f87171', fontWeight: '700', marginTop: '0.2rem' }}>
                {predictionData.risk_level}
              </div>
            </div>
          </div>

          {/* Model Confidence Meter */}
          <div style={{
            background: 'rgba(0,0,0,0.35)',
            backdropFilter: 'blur(8px)',
            borderRadius: 'var(--radius-md)',
            padding: '1.25rem 2rem',
            textAlign: 'center',
            minWidth: '200px'
          }}>
            <div style={{ fontSize: '0.75rem', fontWeight: '700', color: 'var(--text-muted)', textTransform: 'uppercase' }}>Model Confidence</div>
            <div style={{ fontSize: '2.5rem', fontWeight: '900', color: '#38bdf8', lineHeight: 1, marginTop: '0.4rem' }}>
              {predictionData.confidence_percentage}%
            </div>
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '0.4rem' }}>{predictionData.model_name} Engine</div>
          </div>
        </div>

        {/* Probability Distribution Bars */}
        <div style={{ marginTop: '2rem', paddingTop: '1.5rem', borderTop: '1px solid rgba(255,255,255,0.1)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', fontWeight: '700', marginBottom: '0.5rem' }}>
            <span style={{ color: '#34d399' }}>Subscribe Probability: {(predictionData.probability_yes * 100).toFixed(1)}%</span>
            <span style={{ color: '#f87171' }}>Do Not Subscribe Probability: {(predictionData.probability_no * 100).toFixed(1)}%</span>
          </div>

          <div style={{ height: '12px', width: '100%', background: 'rgba(239, 68, 68, 0.4)', borderRadius: '6px', overflow: 'hidden', display: 'flex' }}>
            <div style={{ width: `${predictionData.probability_yes * 100}%`, background: '#34d399', height: '100%' }} />
          </div>
        </div>
      </div>

      {/* Explanations & Input Features */}
      <div className="grid-2">
        <div className="card">
          <div className="card-title">
            <Cpu size={20} color="#6366f1" />
            <span>Key Feature Drivers & Reasoning</span>
          </div>

          <ul style={{ paddingLeft: '1.2rem', marginTop: '1rem', color: '#e5e7eb', fontSize: '0.95rem' }}>
            {predictionData.key_factors?.map((factor, idx) => (
              <li key={idx} style={{ marginBottom: '0.75rem', lineHeight: '1.6' }}>
                {factor}
              </li>
            ))}
          </ul>
        </div>

        <div className="card">
          <div className="card-title">
            <ShieldCheck size={20} color="#06b6d4" />
            <span>Submitted Profile Feature Vector</span>
          </div>

          {inputData && (
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem', marginTop: '1rem', fontSize: '0.85rem' }}>
              <div><span style={{ color: 'var(--text-muted)' }}>Age:</span> <strong>{inputData.age} yrs</strong></div>
              <div><span style={{ color: 'var(--text-muted)' }}>Job:</span> <strong style={{ textTransform: 'capitalize' }}>{inputData.job}</strong></div>
              <div><span style={{ color: 'var(--text-muted)' }}>Balance:</span> <strong>${inputData.balance}</strong></div>
              <div><span style={{ color: 'var(--text-muted)' }}>Housing:</span> <strong>{inputData.housing}</strong></div>
              <div><span style={{ color: 'var(--text-muted)' }}>Duration:</span> <strong>{inputData.duration}s</strong></div>
              <div><span style={{ color: 'var(--text-muted)' }}>Campaign:</span> <strong>{inputData.campaign} contact(s)</strong></div>
              <div><span style={{ color: 'var(--text-muted)' }}>Outcome:</span> <strong style={{ textTransform: 'capitalize' }}>{inputData.poutcome}</strong></div>
              <div><span style={{ color: 'var(--text-muted)' }}>Contact:</span> <strong style={{ textTransform: 'capitalize' }}>{inputData.contact}</strong></div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default MLResults;
